---
title: "Model Selection in Factor Analysis"
author: "Zhining Wang"
supervisors:
  - "Dr. Emi Tanaka"
  - "Dr. Qinian Jin (co-supervisor)"
date: today
format: 
  pdf: 
    documentclass: amsart
    fontsize: 12pt
    template-partials:
      - partials/before-body.tex
      - partials/after-body.tex
    include-in-header:
      text: |
        \usepackage{fullpage}
        \usepackage{enumitem}
bibliography: ref.bib
editor: 
  markdown: 
    wrap: 72
---

Notation is presented in @tbl-notation.



# What is factor analysis and why is it important?

Factor analysis is a mathematical model which tries to use fewer
underlying factors to explain the correlation between a large set of
observed variables[@mardiaMultivariateAnalysis1979]. It provides a useful tool for
exploring the covariance structure among observable variables [@hiroseSparseEstimationNonconcave2015]. One of the major assumptions that factor analytic model stands on
is that it is impossible for us to observe those underlying factors
directly. This assumption is especially suited to subjects like
psychology where we cannot observe exactly some concept like how
intelligent our subjects are[@mardiaMultivariateAnalysis1979].

Suppose we have a observable random vector $\mathbf{y}\in \mathbb{R}^p$
with mean $\mathbb{E}[\mathbf{y}]=\mu$ and variance
$\mathbb{V}[\mathbf{y}]=\Sigma$. Then a d-order factor analysis model
for $\mathbf{y}$ can be given by \begin{equation}
\mathbf{y}=\Lambda \mathbf{f}+\mu+\epsilon,
\end{equation} where $\Lambda \in \mathbb{R}^{p \times d}$ is called
\emph{loading matrix}, we call $\mathbf{f} \in \mathbb{R}^{d}$ as
\emph{common vectors} and $\epsilon \in \mathbb{R}^{p}$ is
\emph{unique factors}. To make the model well-defined, we may assume
$$\mathbb{E}[\mathbf{f}]=\mathbf{0}_d, \mathbb{V}[\mathbf{f}]=\mathbf{I}_{d\times d}, \mathbb{E}[\epsilon]=\mathbf{0}_p, \mathbb{V}[\epsilon]=:\Psi=\text{diag}(\psi_{11},\dots,\psi_{pp})$$
and also the independence between any elements from $\mathbf{f}$ and
$\epsilon$ separately, i.e.
$$\mathbf{Cov}[\mathbf{f}_i,\epsilon_j]=0, \text{for all } i\in\{1,2,\dots,d\} \text{ and } j \in \{1,2,\dots,p\}$$
Straightforwardly, the covariance of observable vector $\mathbf{y}$ can
be modelled by\
\begin{equation}
\mathbb{V}[\mathbf{y}]=\Lambda\Lambda^\top+\Psi
\end{equation}

# Indeterminacy of the loading matrix

One can easily see that if our factor analytic model is given by (1),
then it can also be modelled as
$$\mathbf{y}=(\Lambda\mathbf{M})(\mathbf{M}^\top\mathbf{f}) +\mu+\epsilon$$
where the matrix $\mathbf{M}$ is orthogonal and simultaneously the
variance of $\mathbf{y}$ given by (2) still holds, since
$$\mathbb{V}[\mathbf{y}]=(\Lambda\mathbf{M}\mathbf{M}^\top)\mathbb{V}[\mathbf{f}](\Lambda\mathbf{M}\mathbf{M}^\top)^\top+\Psi=\Lambda\Lambda^\top+\Psi.$$
Therefore a rotated loading matrix $\Lambda\mathbf{M}$ is still a valid
loading matrix for a factor analytic model.

# Traditional Estimation of parameters in factor analytic models 
We denote the set of parameters by $\beta := \{\text{vec}(\Lambda),\text{vec}(\Psi)\}$ where $\text{vec}(\cdot)$ is the vectorisation of the input.
Traditionally, a two-step procedure is used to construct a factor
analytic models: estimated parameters by Maximum likelihood estimation
(aka, MLE) and then use rotation techniques to find an interpretable
model.  

## Maximum Likelihood Estimation 
Suppose we have $N$ independent and identically distributed observations
$\mathbf{y}_1,\mathbf{y}_2,\dots,\mathbf{y}_N$ from a p-dimensional
multi-variate normal distribution $N_p(\mu,\Sigma)$ and by our
hypothesis, we have $\Sigma=\Lambda\Lambda^\top+\Psi$. Then the likelihood
function is given by
$$L(\Lambda,\Psi)=\Pi^N_{i=1}\left[(2\pi)^{-\frac{p}{2}}\det(\Sigma)^{-\frac{1}{2}}\exp(-\frac{1}{2}(\mathbf{y}_i-\mu)^\top\Sigma^{-1}(\mathbf{y}_i-\mu))\right].$$
Many algorithms are developed to get the root of the equation
$$ \frac{\partial l}{\partial \Lambda}=0 \text{ and } \frac{\partial l}{\partial \Psi}=0$$ where $l$ is the log-likelihood given by $l(\Lambda,\Psi):=\log(L(\Lambda,\Psi))$.  

## Rotation Techniques
After estimation, we want to rotate the loading matrix to possess a sparse matrix in order to interpret the observable variables by underlying factors better. Also there are many method to achieve rotation as well such as the varimax method and the promax method [@hiroseSparseEstimationNonconcave2015].


# Penalized Likelihood method
The biggest challenge traditional two-step method facing is unsuitability[@hiroseSparseEstimationNonconcave2015]. Just like in regression models, MLE may lead to overfitness and rotatin techniques may not produce sparse enough loading matrix. In some simulation studies, the two-step method generated bad loading matrix even if the true loading matrix is sparse.[@hiroseSparseEstimationNonconcave2015] Our research later will focus on penalized likelihood method such like LASSO penalty[@ning2011sparsefactoranalysisl1regularization] [@choi2010penalizedmaximumlikelihoodapproach] and may include some non-convex penalty like MC+[@zhang2010variableselectionminimaxconcave].


# Plan

My plan is to   
1. Conduct a detailed examination of the traditional two-step approach, with a particular focus on rotation techniques.  
2. Explore how does the penalized likelihood method work for order-selection and overcome the defects traditional two-step approach are facing.  
3. Explore the implementation of the LASSO penalty in a factor analytic model to enhance model selection and sparsity.  
4. Simulation study   
5. If possible, I may explore linear latent variable models, i.e. the model given by (1) will additionally have a linear term $\beta X$ to fit the mean $\mu$.  


## Appendix


| Notation | Description |
| ---: | --------------------- |
| $A^\top$ | the transpose of the matrix (or vector) $A$ |
| $\mathbb{R}^{p}$ | the space of all p-dimensional real column vectors like $[a_1,a_2,\dots,a_p]^\top$ |
| $\mathbb{R}^{p\times q}$ | the space of all real matrices with size $p\times q$| 
| $\mathbb{E}[\cdot]$| the expectation, or mean of a random variable |
| $\mathbb{V}[\cdot]$ | the variance, or covariance of a random variable |
| $\mathbf{Cov}[\cdot , \cdot]$ | the covariance of two random variables |
| $\mathbf{0}_{p}$ and $\mathbf{0}_{p\times q}$ | the p-dimensional $0$ vector or $0$ matrix in size $p\times q$ respectively |
| $\mathbf{I}_p$ | the identity matrix in size $p\times p$ |

: List of notations used in this report. {#tbl-notation}


# References