project:
  type: website
  render: 
    - '*qmd'
    - '!Outputs/'

website:
  title: "test-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

engine: knitr
