# Appendix 


## Multivariate Normal distribution

Suppose that a $p$-vector random variable $\boldsymbol{y} \sim N_p(\boldsymbol{\mu},\mathbf{\Sigma})$, then the probability density function of $\boldsymbol{y}$ is given as:

$$f(\boldsymbol{y}) = (2\pi)^{-\frac{p}{2}}|\boldsymbol{\Sigma}|^{-\frac{1}{2}}\exp\left(-\frac{1}{2}(\boldsymbol{y}-\boldsymbol{\mu})^\top\boldsymbol{\Sigma}^{-1}(\boldsymbol{y}-\boldsymbol{\mu})\right).$$

$$\log f(\boldsymbol{y}) = -\frac{p}{2}\log(2\pi)-\frac{1}{2}\log|\boldsymbol{\Sigma}|-\frac{1}{2}(\boldsymbol{y}-\boldsymbol{\mu})^\top\boldsymbol{\Sigma}^{-1}(\boldsymbol{y}-\boldsymbol{\mu}).$$

## Conditional 

:::{#lem-cond} 

If $\boldsymbol{\alpha}\sim N(\boldsymbol{\mu}_{\boldsymbol{\alpha}},\boldsymbol{\Sigma_{\boldsymbol{\alpha}}})$ and $\boldsymbol{\beta}\sim N(\boldsymbol{\mu}_{\boldsymbol{\beta}},\boldsymbol{\Sigma}_{\boldsymbol{\beta}})$, then we have $\boldsymbol{\alpha}|\boldsymbol{\beta}\sim N(\boldsymbol{\mu}_{\boldsymbol{\alpha}|\boldsymbol{\beta}},\boldsymbol{\Sigma}_{\boldsymbol{\alpha}|\boldsymbol{\beta}})$, where 
$$
\begin{align*}
& \boldsymbol{\mu}_{\boldsymbol{\alpha}}|\boldsymbol{\beta}=\boldsymbol{\mu}_{\boldsymbol{\alpha}}+\boldsymbol{Cov}[\boldsymbol{\alpha},\boldsymbol{\beta}]\boldsymbol{\Sigma}_{\boldsymbol{\beta}}^{-1}\boldsymbol{\beta}\\
& \boldsymbol{\Sigma}_{\boldsymbol{\alpha}|\boldsymbol{\beta}}= \boldsymbol{\Sigma}_{\boldsymbol{\alpha}}-\boldsymbol{Cov}[\boldsymbol{\alpha},\boldsymbol{\beta}]\boldsymbol{\Sigma}_{\boldsymbol{\beta}}^{-1}\boldsymbol{Cov}[\boldsymbol{\alpha},\boldsymbol{\beta}]^\top.
\end{align*}
$$
:::



::: {#lem-con-distribution}
Let $\boldsymbol{x}\sim \mathcal{N}(\boldsymbol{\mu}_1,\boldsymbol{\Sigma}_1)$ and $\boldsymbol{y}\sim \mathcal{N}(\boldsymbol{\mu}_2,\boldsymbol{\Sigma}_2)$, by definition of multivariate normal distribution, we have 
$$
\begin{pmatrix}
\boldsymbol{x}\\
\boldsymbol{y}
\end{pmatrix}
\sim \mathcal{N}(
\begin{pmatrix}
\boldsymbol{\mu_x}\\
\boldsymbol{\mu_y}
\end{pmatrix}
,
\begin{pmatrix}
\boldsymbol{\Sigma_{xx}} & \boldsymbol{\Sigma_{xy}}\\
\boldsymbol{\Sigma_{yx}} & \boldsymbol{\Sigma_{yy}}
\end{pmatrix}
).
$$
The conditional distribution $\boldsymbol{x}|\boldsymbol{y}$ is then given by 
$$
\boldsymbol{x}|\boldsymbol{y} \sim \mathcal{N}(\boldsymbol{\mu_{x|y}},\boldsymbol{\Sigma_{x|y}}),
$$
where
$$
\begin{align*}
& \boldsymbol{\mu_{x|y}} = \boldsymbol{\mu_x}+\boldsymbol{\Sigma_{xy}}\boldsymbol{\Sigma_{yy}}^{-1}(\boldsymbol{y}-\boldsymbol{\mu_y})\\
& \boldsymbol{\Sigma_{x|y}} = \boldsymbol{\Sigma_{xx}}-\boldsymbol{\Sigma_{xy}}\boldsymbol{\Sigma_{yy}}^{-1}\boldsymbol{\Sigma_{yx}}
\end{align*}.
$$
:::
::: proof
See Appendix A.
:::
